spring:
  datasource:
    username: ENC(wOSSeLozF5y20roVn6HL6wdOsuZ+2Hnt)
    password: ENC(XkxtHQp7dawTFYVIVp4Zmg==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #카멜<->스네이크
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(0lAnV4gciTGJgqFKCLO0lyJio73qXW1BCrvHedvYTziZ5Oz527G8yjPqRdTv8QqH1UF/2wW0Lp88pJJLV23MV4ZYRomYJQKyN9H3DwyQszdrasmRgRgQRA==)
            client-secret: ENC(Uljy5dv7PALwaPbKVYCUzFXdjMg1+WGdagGFJZe2430roT62zQEt1J4Jbt2vauid)
            redirect-uri: "{baseUrl}/oauth2/cb/{registrationId}"
            scope: email, profile

          naver:
            client-id: ENC(Louf0x8KA52pwg2e9Wrg0KQQmxgULkR/0WxDt/7p/ig=)
            client-secret: ENC(CedVXw2pFEWr3W/9TEYDQ1uognKSOMKr)
            client-name: Naver
            redirect-uri: "{baseUrl}/oauth2/cb/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email

          kakao:
            client-id: ENC(Up8yHYclyQQOotd2EF3xr7Pnym9GRu3e6L1rBcJdbcfYkaRfti56srD2HuNqjGxW)
            client-secret: ENC(5mhweRtMMlW1jD+OhUOwb4czH0t3GOoKRCp5ovnuavz3dxa3I6pYJ8Q7pC2itUOB)   # 카카오는 선택값
            client-name: Kakao
            redirect-uri: "{baseUrl}/oauth2/cb/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: profile_nickname, account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cors:
  allowed-origins: "http://localhost:5173,http://13.239.186.180"

jwt:
  secret: ENC(5o9Cw1Z/TL0mzoYYUU+m/6YK1HyaumDraAFuOhkCPkODkVYrb7Ge01mlMG4ovWTc04R1tyBE4z4=)

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j