spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cho?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8888