spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cho?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080