spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cho?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

server:
  port: 8888

app:
  front-base-url: http://localhost:5173

logging:
  file:
    name: C:\app_logs\my-library\springboot.log
  level:
    root: info
    org.hibernate.sql: DEBUG