spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cho?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

server:
  port: 8888
  address: 127.0.0.1 #외부 접속 차단

app:
  front-base-url: http://13.239.186.180:80

#logging:
#  file:
#    name: /var/log/my-library/springboot.log
#  level:
#    root: info
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE   # 바인딩 값까지 보고 싶다면 추가