spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cho?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ENC(GzoKiF5s6bYyG/0fCs6zpaKENwRyvCjg)
    password: ENC(VcSu9hzNHpuPgzkhmH+qkQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update    # 또는 none, validate, create, create-drop
    show-sql: true         # 콘솔에 SQL 출력 여부
    properties:
      hibernate:
        format_sql: true   # SQL 보기 좋게 정렬
    open-in-view: false    # (권장) 서비스-DB 연결을 명확히 끊어줌

  # optional: timezone 설정
  jackson:
    time-zone: Asia/Seoul

server:
  port: 8080
